apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-db-deployment
  labels:
    app: accountdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accountdb
  template:
    metadata:
      labels:
        app: accountdb
    spec:
      containers:
        - name: accountdb
          image: mongodb:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_DB
              value: accountdb
              # - name: POSTGRES_PASSWORD
              #   valueFrom:
              #     secretKeyRef:
              #       name: accountdb-secret
              #       key: postgres-root-password
              # - name: POSTGRES_DATABASE
              #   valueFrom:
              #     configMapKeyRef:
              #       name: accountdb-config
              #       key: db_name
---
apiVersion: v1
kind: Service
metadata:
  name: account-db-service
spec:
  selector:
    app: accountdb
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---
apiVersion: v1
kind: Secret
metadata:
  name: accountdb-secret
type: Opaque
stringData:
  mysql-root-password: password
  mysql_root_username: postgres
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: accountdb-config
data:
  db_name: accountdb
