apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-db-deployment
  labels:
    app: orderdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderdb
  template:
    metadata:
      labels:
        app: orderdb
    spec:
      containers:
        - name: orderdb
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_DB
              value: orderdb
            # - name: POSTGRES_PASSWORD
            #   valueFrom:
            #     secretKeyRef:
            #       name: orderdb-secret
            #       key: postgres-root-password
            # - name: POSTGRES_DATABASE
            #   valueFrom:
            #     configMapKeyRef:
            #       name: orderdb-config
            #       key: db_name
---
apiVersion: v1
kind: Service
metadata:
  name: order-db-service
spec:
  selector:
    app: orderdb
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---
apiVersion: v1
kind: Secret
metadata:
  name: orderdb-secret
type: Opaque
stringData:
  mysql-root-password: password
  mysql_root_username: postgres
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: orderdb-config
data:
  db_name: orderdb
