apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-db-deployment
  labels:
    app: productdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productdb
  template:
    metadata:
      labels:
        app: productdb
    spec:
      containers:
        - name: productdb
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_DB
              value: productdb
          # env:
          #   - name: POSTGRES_PASSWORD
          #     valueFrom:
          #       secretKeyRef:
          #         name: productdb-secret
          #         key: postgres-root-password
          #   - name: POSTGRES_DATABASE
          #     valueFrom:
          #       configMapKeyRef:
          #         name: productdb-config
          #         key: db_name
---
apiVersion: v1
kind: Service
metadata:
  name: product-db-service
spec:
  selector:
    app: productdb
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---
apiVersion: v1
kind: Secret
metadata:
  name: productdb-secret
type: Opaque
stringData:
  mysql-root-password: password
  mysql_root_username: postgres
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: productdb-config
data:
  db_name: productdb
